#!/bin/sh

# Autostart programs
HOSTNAME=$(hostname)
if [ "$HOSTNAME" = klar-arch ]; then
    monitor=$(xrandr | awk '/\<connected\>/ {print $1}')
	killall xrandr; xrandr --output "$monitor" --mode 1920x1080 --rate 144 &
fi
# setxkbmap si -option caps:escape_shifted_capslock &
# setxkbmap si -option 'caps:swapescape' -option 'caps:ctrl_modifier'; xmodmap -e 'keycode 255 = Escape'; xcape -e '#66=Escape' &
setxkbmap -layout si,ru -variant ,phonetic -option 'caps:swapescape' -option 'caps:ctrl_modifier' -option 'grp:alt_space_toggle'; xmodmap -e 'keycode 255 = Escape'; xcape -e '#66=Escape' &
killall sxhkd; sxhkd &
killall picom; sleep 0.1s; picom &
killall dunst; dunst &
killall nm-applet; nm-applet &
killall blueman-applet; blueman-applet &
killall mpd; mpd &
killall gummy; gummy start &
thunar --daemon &
feh --bg-fill ~/Pictures/gruvbox_walls/stairs.jpg &
emacs --daemon && notify-send --icon=/usr/share/emacs/28.2/etc/images/icons/hicolor/scalable/apps/emacs.ico "Emacs daemon started" &

sh -c '$HOME/.config/polybar/launch.sh' &

# Variable
alias bc='bspc config'
alias br='bspc rule'

# Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Others
bc border_width         0
#bc border_radius        15
bc window_gap           12
bc split_ratio          0.52
bc borderless_monocle   true
bc gapless_monocle      true

# Rules
# br -a mpv state=floating
# br -a feh state=floating
# br -a sxiv state=floating
br -a nm-connection-editor state=floating
br -a Zathura state=tiled
br -a Emacs state=tiled
