#! /bin/sh

# Autostart programs
killall sxhkd; sxhkd &
#killall xrandr; xrandr --output HDMI-1 --mode 1920x1080 --rate 144 &
killall picom; picom &
killall deadd-notification-center; deadd-notification center &
killall nitrogen; nitrogen --restore &
killall nm-applet; nm-applet &
killall blueman-applet; blueman-applet &
killall thunar; thunar --daemon &
killall mpd; mpd &
setxkbmap si -option caps:swapescape &
emacs --daemon &

xinput set-prop 12 340 1 &
xinput set-prop 11 318 1 &
xinput set-prop 11 320 1 &
xinput set-prop 10 318 1 &
sh -c '~/.config/polybar/launch.sh' &

# Variable
alias bc='bspc config'
alias br='bspc rule'

# Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Others
bc border_width         0
#bc border_radius        15
bc window_gap           12
bc split_ratio          0.52
bc borderless_monocle   true
bc gapless_monocle      true

# Rules
br -a mpv state=floating
br -a feh state=floating
br -a sxiv state=floating
br -a nm-connection-editor state=floating
br -a Zathura state=tiled
br -a Emacs state=tiled
